paths:
  /api/products/:
    get:
      summary: Get all the products
      tags:
        - Products
      responses:
        "200":
          description: The products were successfully obtained from the database
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Product"
        "500":
          description: Error in the server, posibly an error in the connection with the database
    post:
      summary: Add products to the database
      tags:
        - Products
      responses:
        "200": 
          description: Products successfully saved in the database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#components/requestBodies/updateProduct"    
  /api/products/{pid}:
    get:
      summary: Get a product from the database with its id
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: Id of the product to obtain
          schema:
            $type: String
      responses:
        "200": 
          description: Product obtained from the database
          content:
            application/json:
              schema:
                $ref: "#components/schemas/Product"
    put:
      summary: Updates a product from the database
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: id of the product to update
          schema:
            $type: String
      responses:
        "200": 
          description: Product updated from the database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#components/requestBodies/updateProduct" 
    delete:
      summary: deletes a product from the database
      tags:
        - Products
      parameters:
        - name: pid
          required: true
          description: id of the product to delete from the database
          schema:
            $type: String
      responses:
        "200": 
          description: Product deleted from the database
components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: ObjectId
          description: Id autogenerated from mongo
        title:
          type: String
          description: Title of the product
        description:
          type: String
          description: Details of the product
        code:
          type: String
          description: Code to indentify the product
        price:
          type: Number
          description: Price of the product
        category:
          type: String
          description: Group where the product belongs
        stock:
          type: Number
          description: quantity real of the product in existence
        status:
          type: Boolean
          description: If the product has enough stock
        thumbnails:
          type: array
          description: Array where the images of the products can be saved
      example:
        _id: ObjectId("as21321dsfdfs3d3fdfsd3g")
        title: Micro Procesador Ryzen 5
        description: Clave en el rendimiento de tu computadora de escritorio
        code: PR03
        price: 100
        category: procesador
        stock: 20
        status: true
        thumbnails: [
          http://localhost:8080/images/1685905000427-Micro-Procesador-Ryzen-5-4500-6-Nucleos-4.1ghz-Amd-Ddr4.png]
  requestBodies:
    updateProduct:
      type: object
      properties:
        title: 
          type: String
          description: Title of the product
        description: 
          type: String
          description: Details of the product
        code: 
          type: String
          description: Code to indentify the product
        price: 
          type: Number
          description: Price of the product
        category: 
          type: String
          description: Group where the product belongs
        stock: 
          type: Number
          description: quantity real of the product in existence
        status: 
          type: Boolean
          description: If the product has enough stock
        thumbnails: 
          type: array
          description: Array where the images of the products can be saved
      example:
        title: Micro Procesador
        description: Clave en el rendimiento de tu computadora de escritorio
        code: PREJ
        price: 1000
        category: procesador
        stock: 205
        status: true
        thumbnails: [
          http://localhost:8080/images/1685905000427-Micro-Procesador-Ryzen-5-4500-6-Nucleos-4.1ghz-Amd-Ddr4.png]

